# Generated by Django 3.1.5 on 2021-01-05 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20210105_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
